name: Generate Snake

on:
  # This runs the workflow every time you push to your main branch...
  push:
    branches:
      - main
  # ...and also on a schedule (below: runs weekly on Sunday at 00:00).
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the current repository
      - name: Checkout
        uses: actions/checkout@v3

      # 2) Generate the Snake SVG
      - name: Generate Snake
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: kush551  # Your GitHub username
          outputs: dist/snake.svg

      # 3) Upload the Snake as an artifact
      - name: Upload snake.svg
        uses: actions/upload-artifact@v2
        with:
          name: snake.svg
          path: dist/snake.svg
